function out = runAVL_aileronCase_JAGER(p)
% ============================================================
% runAVL_aileronCase_JAGER
%
% Evaluates ONE aileron geometry case using AVL.
% Returns derivatives, hinge metrics, and roll-authority metrics.
% ============================================================

    out = struct();
    out.success = false;
    out.errMsg  = "";

    try
        %% -----------------------------------------
        % 1) DERIVED GEOMETRY FOR THIS CASE
        %% -----------------------------------------
        eta_a0     = p.eta_a0;
        Xhinge_ail = p.Xhinge_ail;

        y_a0 = eta_a0 * p.b2;

        % V-tail shared stations
        eta0 = 0.0;
        eta1 = p.eta_rv0;
        eta2 = 1.0;

        y0p = eta0*abs(p.yT); z0 = eta0*p.zT;
        y1p = eta1*abs(p.yT); z1 = eta1*p.zT;
        y2p = eta2*abs(p.yT); z2 = eta2*p.zT;

        c0 = p.c_root_vt + (p.c_tip_vt - p.c_root_vt)*eta0;
        c1 = p.c_root_vt + (p.c_tip_vt - p.c_root_vt)*eta1;
        c2 = p.c_root_vt + (p.c_tip_vt - p.c_root_vt)*eta2;

        x0 = p.XtailLE_root + y0p*tand(p.LambdaLE_deg);
        x1 = p.XtailLE_root + y1p*tand(p.LambdaLE_deg);
        x2 = p.XtailLE_root + y2p*tand(p.LambdaLE_deg);

        %% -----------------------------------------
        % 2) WRITE GEOMETRY FILE
        %% -----------------------------------------
        fid = fopen(p.geomFile,'w');
        assert(fid>0, "Could not write geometry file.");

        fprintf(fid,"JAGER Geometry sweep case (generated by MATLAB)\n");
        fprintf(fid,"%.4f\n", p.Mach);
        fprintf(fid,"0 0 0.0\n");
        fprintf(fid,"%.4f %.4f %.4f\n", p.Sref, p.Cref, p.Bref);
        fprintf(fid,"%.4f %.4f %.4f\n", p.Xref, p.Yref, p.Zref);
        fprintf(fid,"%.6f\n\n", p.CDp);

        % Wing
        fprintf(fid,"SURFACE\nWing\n");
        fprintf(fid,"10 1.0 24 1.0\n");
        fprintf(fid,"YDUPLICATE\n0.0\n\n");

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f 0.0000 0.0000 %.4f 0.0000\n", p.XwingLE, p.c_w);
        write_airfoil(fid, p.wing_airfoil_type, p.wing_naca, "");

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f %.4f 0.0000 %.4f 0.0000\n", p.XwingLE, y_a0, p.c_w);
        write_airfoil(fid, p.wing_airfoil_type, p.wing_naca, "");
        fprintf(fid,"CONTROL\n");
        fprintf(fid,"aileron %.3f %.3f 0 0 0 %.1f\n\n", ...
            p.aileron_gain, Xhinge_ail, p.aileron_SgnDup);

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f %.4f 0.0000 %.4f 0.0000\n", p.XwingLE, p.y_tip, p.c_w);
        write_airfoil(fid, p.wing_airfoil_type, p.wing_naca, "");
        fprintf(fid,"CONTROL\n");
        fprintf(fid,"aileron %.3f %.3f 0 0 0 %.1f\n\n", ...
            p.aileron_gain, Xhinge_ail, p.aileron_SgnDup);

        % Vtail Right
        fprintf(fid,"SURFACE\nVtail_R\n");
        fprintf(fid,"8 1.0 16 1.0\n\n");

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f %.4f %.4f %.4f 0.0000\n", x0, +y0p, z0, c0);
        write_airfoil(fid, p.vtail_airfoil_type, p.vtail_naca, "");

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f %.4f %.4f %.4f 0.0000\n", x1, +y1p, z1, c1);
        write_airfoil(fid, p.vtail_airfoil_type, p.vtail_naca, "");

        fprintf(fid,"CONTROL\n");
        fprintf(fid,"pitchv %.3f %.3f 0 0 0 1.0\n", +p.pitchv_gain, p.Xhinge_rv);
        fprintf(fid,"CONTROL\n");
        fprintf(fid,"yawv %.3f %.3f 0 0 0 1.0\n\n", +p.yawv_gain, p.Xhinge_rv);

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f %.4f %.4f %.4f 0.0000\n", x2, +y2p, z2, c2);
        write_airfoil(fid, p.vtail_airfoil_type, p.vtail_naca, "");

        fprintf(fid,"CONTROL\n");
        fprintf(fid,"pitchv %.3f %.3f 0 0 0 1.0\n", +p.pitchv_gain, p.Xhinge_rv);
        fprintf(fid,"CONTROL\n");
        fprintf(fid,"yawv %.3f %.3f 0 0 0 1.0\n\n", +p.yawv_gain, p.Xhinge_rv);

        % Vtail Left
        fprintf(fid,"SURFACE\nVtail_L\n");
        fprintf(fid,"8 1.0 16 1.0\n\n");

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f %.4f %.4f %.4f 0.0000\n", x0, -y0p, z0, c0);
        write_airfoil(fid, p.vtail_airfoil_type, p.vtail_naca, "");

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f %.4f %.4f %.4f 0.0000\n", x1, -y1p, z1, c1);
        write_airfoil(fid, p.vtail_airfoil_type, p.vtail_naca, "");

        fprintf(fid,"CONTROL\n");
        fprintf(fid,"pitchv %.3f %.3f 0 0 0 1.0\n", -p.pitchv_gain, p.Xhinge_rv);
        fprintf(fid,"CONTROL\n");
        fprintf(fid,"yawv %.3f %.3f 0 0 0 1.0\n\n", +p.yawv_gain, p.Xhinge_rv);

        fprintf(fid,"SECTION\n");
        fprintf(fid,"%.4f %.4f %.4f %.4f 0.0000\n", x2, -y2p, z2, c2);
        write_airfoil(fid, p.vtail_airfoil_type, p.vtail_naca, "");

        fprintf(fid,"CONTROL\n");
        fprintf(fid,"pitchv %.3f %.3f 0 0 0 1.0\n", -p.pitchv_gain, p.Xhinge_rv);
        fprintf(fid,"CONTROL\n");
        fprintf(fid,"yawv %.3f %.3f 0 0 0 1.0\n\n", +p.yawv_gain, p.Xhinge_rv);

        fclose(fid);

        %% -----------------------------------------
        % 3) WRITE MASS FILE
        %% -----------------------------------------
        fid = fopen(p.massFile,'w');
        assert(fid>0, "Could not write mass file.");

        fprintf(fid,"# Jager mass file (generated by MATLAB)\n");
        fprintf(fid,"# mass  x  y  z  Ixx  Iyy  Izz  Ixz  Ixy  Iyz\n");
        fprintf(fid,"# mass units: slug\n");
        fprintf(fid,"# length units: ft\n");
        fprintf(fid,"# inertia units: slug*ft^2\n");
        fprintf(fid,"%.6f  %.6f  %.6f  %.6f  %.6f  %.6f  %.6f  %.6f  %.6f  %.6f\n", ...
            p.m_slug, p.Xcg_ft, p.Ycg_ft, p.Zcg_ft, ...
            p.Ixx, p.Iyy, p.Izz, p.Ixz, p.Ixy, p.Iyz);

        fclose(fid);

        %% -----------------------------------------
        % 4) RUN BASELINE / POS / NEG
        %% -----------------------------------------
        out0 = run_one_case_internal(p, p.delta0);
        outP = run_one_case_internal(p, p.deltaP);
        outM = run_one_case_internal(p, p.deltaM);

        %% -----------------------------------------
        % 5) EXTRACT DEFLECTIONS
        %% -----------------------------------------
        deltaPlusEcho  = get_control_value(outP.FT.controls, p.controlName);
        deltaMinusEcho = get_control_value(outM.FT.controls, p.controlName);

        if isnan(deltaPlusEcho) || isnan(deltaMinusEcho)
            error("Could not find echoed control '%s' in FT output.", p.controlName);
        end

        den = deltaPlusEcho - deltaMinusEcho;
        if abs(den) < 1e-12
            error('Deflection denominator is zero.');
        end

        %% -----------------------------------------
        % 6) DERIVATIVES
        %% -----------------------------------------
        dCl_dDelta = (outP.FT.Cl - outM.FT.Cl) / den;
        dCm_dDelta = (outP.FT.Cm - outM.FT.Cm) / den;
        dCn_dDelta = (outP.FT.Cn - outM.FT.Cn) / den;
        dCY_dDelta = (outP.FT.CY - outM.FT.CY) / den;
        dCL_dDelta = (outP.FT.CL - outM.FT.CL) / den;
        dCD_dDelta = (outP.FT.CD - outM.FT.CD) / den;

        %% -----------------------------------------
        % 7) ROLL AUTHORITY ESTIMATE
        %% -----------------------------------------
        Cl_avail_10deg = dCl_dDelta * p.delta_cmd_deg;
        L_avail_10deg  = Cl_avail_10deg * p.qbar * p.Sref * p.Bref;
        pdot_10deg     = L_avail_10deg / p.Ixx;
        pdot_10deg_deg = pdot_10deg * 180/pi;

        %% -----------------------------------------
        % 8) HINGE METRICS
        %% -----------------------------------------
        Chinge_plus    = get_hinge_value(outP.HM, p.controlName, 'Chinge');
        Chinge_minus   = get_hinge_value(outM.HM, p.controlName, 'Chinge');
        Hmoment_plus   = get_hinge_value(outP.HM, p.controlName, 'moment_Nm');
        Hmoment_minus  = get_hinge_value(outM.HM, p.controlName, 'moment_Nm');

        Chinge_abs_max  = max(abs([Chinge_plus, Chinge_minus]));
        Hmoment_abs_max = max(abs([Hmoment_plus, Hmoment_minus]));

        %% -----------------------------------------
        % 9) RETURN OUTPUT
        %% -----------------------------------------
        out.success = true;
        out.errMsg  = "";

        out.inputs.eta_a0     = eta_a0;
        out.inputs.Xhinge_ail = Xhinge_ail;

        out.echo.deltaPlus  = deltaPlusEcho;
        out.echo.deltaMinus = deltaMinusEcho;

        out.baseline = out0;
        out.positive = outP;
        out.negative = outM;

        out.derivs.dCl_dDelta = dCl_dDelta;
        out.derivs.dCm_dDelta = dCm_dDelta;
        out.derivs.dCn_dDelta = dCn_dDelta;
        out.derivs.dCY_dDelta = dCY_dDelta;
        out.derivs.dCL_dDelta = dCL_dDelta;
        out.derivs.dCD_dDelta = dCD_dDelta;

        out.roll.Cl_avail_10deg = Cl_avail_10deg;
        out.roll.L_avail_10deg  = L_avail_10deg;
        out.roll.pdot_10deg     = pdot_10deg;
        out.roll.pdot_10deg_deg = pdot_10deg_deg;

        out.hinge.Chinge_plus     = Chinge_plus;
        out.hinge.Chinge_minus    = Chinge_minus;
        out.hinge.Chinge_abs_max  = Chinge_abs_max;
        out.hinge.Hmoment_plus    = Hmoment_plus;
        out.hinge.Hmoment_minus   = Hmoment_minus;
        out.hinge.Hmoment_abs_max = Hmoment_abs_max;

        out.geom.y_a0        = y_a0;
        out.geom.x_hinge_ail = p.XwingLE + Xhinge_ail*p.c_w;
        out.geom.x0 = x0; out.geom.x1 = x1; out.geom.x2 = x2;
        out.geom.y0p = y0p; out.geom.y1p = y1p; out.geom.y2p = y2p;
        out.geom.z0 = z0; out.geom.z1 = z1; out.geom.z2 = z2;
        out.geom.c0 = c0; out.geom.c1 = c1; out.geom.c2 = c2;

    catch ME
        out.success = false;
        out.errMsg  = ME.message;
    end
end

%% ============================================================
% INTERNAL ONE-RUN HELPER
% ============================================================
function out = run_one_case_internal(p, controlValue)

    safeDelete(p.cmdFile);
    safeDelete(p.logFile);

    touch_empty(p.ftFile);
    touch_empty(p.hmFile);

    fid = fopen(p.cmdFile,'w');
    assert(fid>0, "Could not write AVL command file.");

    fprintf(fid,"LOAD %s\n", p.geomFile);
    fprintf(fid,"MASS %s\n", p.massFile);
    fprintf(fid,"OPER\n");
    fprintf(fid,"A A %.6f\n", p.alpha_deg);
    fprintf(fid,"B B %.6f\n", p.beta_deg);
    fprintf(fid,"%s %s %.6f\n", p.controlMenu, p.controlMenu, controlValue);
    fprintf(fid,"X\n");

    fprintf(fid,"FT\n");
    fprintf(fid,"%s\n", p.ftFile);
    fprintf(fid,"O\n");

    fprintf(fid,"HM\n");
    fprintf(fid,"%s\n", p.hmFile);
    fprintf(fid,"O\n");

    fprintf(fid,"\n");
    fprintf(fid,"QUIT\n");
    fclose(fid);

    syscmd = sprintf('"%s" < "%s" > "%s"', p.avlExe, p.cmdFile, p.logFile);
    [status, ~] = system(syscmd);

    if ~isfile(p.ftFile)
        error("FT output file was not created.");
    end

    if status ~= 0
        warning("AVL returned nonzero exit status, but FT file was created. Continuing.");
    end

    out = struct();
    out.FT = parseFTfile(p.ftFile);

    if isfile(p.hmFile)
        out.HM = parseHMfile(p.hmFile);
    else
        out.HM = struct('name',{},'Chinge',{},'deflection_deg',{},'moment_Nm',{});
    end
end

%% ============================================================
% PARSERS / HELPERS
% ============================================================
function FT = parseFTfile(ftFile)
    txt = fileread(ftFile);

    FT = struct();
    FT.CL = grabScalar(txt, 'CLtot');
    FT.CD = grabScalar(txt, 'CDtot');
    FT.CY = grabScalar(txt, 'CYtot');
    FT.Cl = grabScalar(txt, 'Cltot');
    FT.Cm = grabScalar(txt, 'Cmtot');
    FT.Cn = grabScalar(txt, 'Cntot');
    FT.controls = parseControlEchoes(txt);
end

function HM = parseHMfile(hmFile)
    txt = fileread(hmFile);
    lines = regexp(txt, '\r\n|\n|\r', 'split');

    HM = struct('name',{},'Chinge',{},'deflection_deg',{},'moment_Nm',{});

    for i = 1:numel(lines)
        line = strtrim(lines{i});

        tok = regexp(line, ...
            '^([A-Za-z0-9_\-]+)\s+([-+]?\d*\.?\d+(?:[Ee][-+]?\d+)?)\s+([-+]?\d*\.?\d+(?:[Ee][-+]?\d+)?)\s+([-+]?\d*\.?\d+(?:[Ee][-+]?\d+)?)$', ...
            'tokens', 'once');

        if ~isempty(tok)
            s = struct();
            s.name           = string(tok{1});
            s.Chinge         = str2double(tok{2});
            s.deflection_deg = str2double(tok{3});
            s.moment_Nm      = str2double(tok{4});
            HM(end+1) = s; %#ok<AGROW>
        end
    end
end

function x = grabScalar(txt, label)
    pat = [label '\s*=\s*([-+]?\d*\.?\d+(?:[Ee][-+]?\d+)?)'];
    tok = regexp(txt, pat, 'tokens', 'once');
    if isempty(tok)
        error('Could not find %s in FT file.', label);
    end
    x = str2double(tok{1});
end

function controls = parseControlEchoes(txt)
    controls = struct('name',{},'value_deg',{});

    lines = regexp(txt, '\r\n|\n|\r', 'split');
    skipNames = ["CLtot","CDtot","CYtot","Cltot","Cmtot","Cntot", ...
                 "CXtot","CZtot","CDvis","CDind","CLff","CDff","CYff", ...
                 "Alpha","Beta","Mach"];

    for i = 1:numel(lines)
        line = strtrim(lines{i});

        tok = regexp(line, ...
            '^([A-Za-z0-9_\-]+)\s*=\s*([-+]?\d*\.?\d+(?:[Ee][-+]?\d+)?)$', ...
            'tokens', 'once');

        if ~isempty(tok)
            nm = string(tok{1});
            if ~ismember(nm, skipNames)
                s = struct();
                s.name = nm;
                s.value_deg = str2double(tok{2});
                controls(end+1) = s; %#ok<AGROW>
            end
        end
    end
end

function val = get_control_value(ctrls, targetName)
    val = NaN;
    for k = 1:numel(ctrls)
        if string(ctrls(k).name) == string(targetName)
            val = ctrls(k).value_deg;
            return;
        end
    end
end

function val = get_hinge_value(HM, targetName, fieldName)
    val = NaN;
    for k = 1:numel(HM)
        if string(HM(k).name) == string(targetName)
            val = HM(k).(fieldName);
            return;
        end
    end
end

function safeDelete(fname)
    if isfile(fname)
        delete(fname);
    end
end

function touch_empty(fname)
    fid = fopen(fname,'w');
    if fid >= 0
        fclose(fid);
    else
        error("Could not create placeholder file: %s", fname);
    end
end

function write_airfoil(fid, airfoil_type, naca_code, afile)
    switch upper(string(airfoil_type))
        case "NACA"
            fprintf(fid,"NACA\n");
            fprintf(fid,"%s\n\n", string(naca_code));
        case "AFILE"
            fprintf(fid,"AFILE\n");
            fprintf(fid,"%s\n\n", string(afile));
        otherwise
            error("Unsupported airfoil type: %s", string(airfoil_type));
    end
end